name: media_info_example
description: Demonstrates how to use the media_info plugin.
publish_to: 'none'

dependencies:
  file_picker: ^1.11.0+3
  path_provider: ^1.6.10
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  media_info:
    path: ../

flutter:
  uses-material-design: true
