name: media_info
description: Determine multimedia file properties like width, height, duration
version: 0.12.0+2
homepage: https://github.com/ened/flutter_plugin_media_info

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.12.13+hotfix.6"

dependencies:
  mime: ^1.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.1.2
  mockito: ^5.0.16
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
    
flutter:
  plugin:
    platforms:
      android:
        package: asia.ivity.mediainfo
        pluginClass: MediaInfoPlugin
      ios:
        pluginClass: IVMediaInfoPlugin
